### ISSUE TITLE
Drawings file grayed out on iCloud Drive and declined any operation

### ISSUE THREAD

**Issue by sonjadahl** [0si43/PiecesOfPaper#34] opened 2020-11-08 09:28 UTC
I had created several drawings and they are now not visible. They have disappeared. I have spoken to the cloud where i back up and they say to complain to you. These are important drawings i need to access them!

**Comment by 0si43** [comment] 2020-11-09 00:39
I’m so sorry for your inconvenient.

Would you check your Files app on iPad?
If you enabled iCloud Drive, you will see Like Paper folder.
If you disabled iCloud Drive, check "On My iPad".

![IMG_0580](https://user-images.githubusercontent.com/45909001/98488633-b8138a00-226d-11eb-8066-d462b5d771e6.jpg)
![IMG_0581](https://user-images.githubusercontent.com/45909001/98488640-bcd83e00-226d-11eb-92e4-a7467543589c.jpg)

You could see "drawings.plist" file in the folder.
This is a data file contain your note data.
Please check the file size and update date.
If file size is over 1MB and update date is your last edition date, your drawing is salvageable!

**Comment by sonjadahl** [comment] 2020-11-09 14:36
[Image.jpeg]

Hi There thanks for your reply
This is a screen shot which does show a large file. How do I retrieve it?
I do love the app - I like its simplicity. There are some improvements I would make though :)
But please can I get my files back first?
Thanks!
Sonja




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 0si43** [comment] 2020-11-09 23:38
Hi, Sonja

> There are some improvements I would make though :)
Yes!
Actually, I feel a need to change data structure of Like Paper...
I'm planning now.(Though, it's not easy)

I cannot see your screenshot on Github.
Please attach it on your web browser?

Nakajima

**Comment by sonjadahl** [comment] 2020-11-12 20:34
[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 0si43** [comment] 2020-11-13 10:42
Sorry...I still CANNOT see the screenshot.
Do not mail, please access below
(You could drag and drop your image on Github page!)

https://github.com/0si43/LikePaper/issues/34

Anyway, I will write the solution!
This solution is base on an assumption you enabled iCloud Drive.
If you don’t use iCloud or turn off it for Like Paper, tell me that and don’t try below steps! 

1) Duplicate `drawings.plist` another name for safe 
2) Finish Like Paper
3) Open `drawings.plist` In Files app
4) Lunch Like Paper
( 5)If you don’t  feel any back-up file, delete the file made on step1)

**Comment by sonjadahl** [comment] 2020-11-20 07:21
The files are there in the cloud but they are not readable by Apple and can’t be opened from within the app. can’t  How do I download/reopen & access these drawings in the App???

**Comment by 0si43** [comment] 2020-11-21 04:34
Okay, I understood your situation!
But I have never experienced such status...

I will research in a few days.

**Comment by 0si43** [comment] 2020-12-15 00:28
Hi Sonja

I had researched for several weeks.
I was really confused.

### Your Next Action
Please call Apple support and explain your situation like,
“I cannot access my file on iCloud Drive. It’s grayed out and cannot received any operation”

### Important information
- You cannot access your document by Files App
  (Not only Like Paper. If you could access it via Files, and could not via Like Paper, it was responsible for my app)
- Can you access another files on iCloud Drive?
  (Probably Apple staff will ask you)

### Research details
It was impossible to reproduce your situation on my device...
But some people reported [iCloud Documents grayed out](https://discussions.apple.com/search?q=icloud%20document%20grayed%20out&page=1&content=filterDiscussions).
There are no related informations about this problem from Apple.
Finally I called Apple support and explained this situation.
They said like below.
“There are many possible causes. So, please your app user(Sonja) call us directly”

### Possible causes
Probably your Apple ID has any trouble like below

- Authorizing Fail
- Storage Limit
- You should response any dialog on Apple web site

### Don’t feel to be sent around...
I know you firstly called Apple support(Oh, actually did not said Apple. Anyway, any support).
Please don’t feel to be sent around...

I hope your problem solved!

Nakajima

**Comment by alreid123** [comment] 2021-05-14 19:33
Hi there,

Same problem here, file vanished from app but is saved in files but no way of opening it...
Have you figured out how to do this yet?
My file is a survey and notes of a kitchen renovation so quite critical, luckily I drew up the kitchen before the file vanished but really need to see the notes I took!
I now take a screenshot of the pages so it’s saved elsewhere but really need this file back! 
I can’t see how Apple support will be able to help with this problem - they will probably just put it back on you...

Thanks,

Al

**Comment by 0si43** [comment] 2021-05-15 01:53
Hi, Al

Sorry for your inconvenience.
I could not reproduce this problem in my device.
So, I contacted Apple Developer Support and explained the situation.
They recommend that iCloud user directly contacted Apple Support, because there are many reason for the problem.

> I can’t see how Apple support will be able to help with this problem - they will probably just put it back on you...

I know you feel like this…
Anyway, please contact Apple Support and tell them about like below↓

https://github.com/0si43/PiecesOfPaper/issues/34#issuecomment-744881866

If the problem will be fixed, it’s just okay.
If it won’t, the cause become more clear and maybe I can fix it…

Nakajima

**Comment by welshtrees** [comment] 2021-05-28 16:26
Has anyone managed to fix this? I’ve lost 3 months of vital work. Please help!

**Comment by 0si43** [comment] 2021-10-04 02:20
This issue is not solved yet, but has left too long.
I closed this issue.

If there is any progress, re-open this issue or make another issue.

**Closed by 0si43** 2021-10-04 02:20 UTC
Labels: bug
